services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cheko_db
      POSTGRES_USER: cheko_user
      POSTGRES_PASSWORD: cheko_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

volumes:
  db_data:
