version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cheko_db
      SPRING_DATASOURCE_USERNAME: cheko_user
      SPRING_DATASOURCE_PASSWORD: cheko_pass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cheko_user
      POSTGRES_PASSWORD: cheko_pass
      POSTGRES_DB: cheko_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
